version: '3'

services:
  backend:
    container_name: 'kupi-backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-compose-kupi
    restart: always
    ports:
     - '4000:3000'
    env_file: .env
    networks:
      - internal

  frontend:
    container_name: 'kupi-frontent'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-compose-kupi
    restart: always
    ports:
     - '5000:80'
    networks:
      - external

  postgres:
    container_name: 'postgres'
    image: postgres:alpine
    env_file: .env
    restart: always
    networks:
      - internal
    volumes:
     - pg_data:/data/postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
  external:


